name: Package Validation

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  validate:
    name: Shared package validation
    uses: Deucarian/Package-Registry/.github/workflows/deucarian-package-validation.yml@2f10d0dcc049b63474c6e96ed929127d93560b33 # Package Registry develop
    with:
      package-config: deucarian-package.json
      registry-ref: 2f10d0dcc049b63474c6e96ed929127d93560b33 # Package Registry develop
